apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dj9kcu18s-python
  janus-idp.io/tekton: dj9kcu18s-python
  backstage.io/kubernetes-id: dj9kcu18s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dj9kcu18s-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
